site_name: cgml
repo_url: https://github.com/CryptoFraudDetection/cgml
site_url: https://CryptoFraudDetection.github.io/cgml
site_description: Repository for the cgml challenge.
site_author: Gabriel Torres Gamez
edit_uri: edit/cgml/docs/
repo_name: CryptoFraudDetection/cgml

nav:
  - Home: index.md
  - CryptoFraudDetection:
      - elasticsearch:
          - data_insertion: CryptoFraudDetection/elasticsearch/data_insertion.md
          - data_retrieval: CryptoFraudDetection/elasticsearch/data_retrieval.md
          - elastic_client: CryptoFraudDetection/elasticsearch/elastic_client.md
      - scraper:
          - comparitech: CryptoFraudDetection/scraper/comparitech.md
          - google_results: CryptoFraudDetection/scraper/google_results.md
          - utils: CryptoFraudDetection/scraper/utils.md
      - utils:
          - enums: CryptoFraudDetection/utils/enums.md
          - exceptions: CryptoFraudDetection/utils/exceptions.md
          - logger: CryptoFraudDetection/utils/logger.md
          - misc: CryptoFraudDetection/utils/misc.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [CryptoFraudDetection]
theme:
  name: material
  feature:
    tabs: true
  features:
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CryptoFraudDetection/cgml

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
